
COLUMN_NAMES =  ['AccountLength',
                 'VMailMessage',
                 'DayMins',
                 'EveMins',
                 'NightMins',
                 'IntlMins',
                 'CustServCalls',
                 'churn',
                 'IntlPlan',
                 'VMailPlan',
                 'DayCalls',
                 'DayCharge',
                 'EveCalls',
                 'EveCharge',
                 'NightCalls',
                 'NightCharge',
                 'IntlCalls',
                 'IntlCharge',
                 'State',
                 'AreaCode',
                 'Phone']

COLUMN_BOXPLOTS = ['AccountLength',
                 'VMailMessage',
                 'DayMins',
                 'EveMins',
                 'NightMins',
                 'IntlMins',
                 'CustServCalls',
                 'DayCalls',
                 'DayCharge',
                 'EveCalls',
                 'EveCharge',
                 'NightCalls',
                 'NightCharge',
                 'IntlCalls',
                 'IntlCharge',
                 ]


FEATURES = ['DayMins','EveMins','NightMins','IntlMins','CustServCalls','IntlPlan','DayCharge','EveCharge','NightCharge','IntlCharge']